#!/usr/bin/env bash

# Generate docker-compose.yml file for different git branch
# production and staging branchs generate two docker-compose yaml file

# Need a docker-compose-template.txt file to init start

export BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "staging" -o "$BRANCH" = "dev" ]; then
    export HTTP_PORT='"8000:80"' HTTPS_PORT='"4443:443"'
elif [ "$BRANCH" = "production" ]; then
    export HTTP_PORT='"80:80"' HTTPS_PORT='"443:443"'
fi

export PRJ_NAME=$(git remote -v  | grep fetch | sed "s#^.*/\(.*\).git (fetch)#\1#")

# single quotes here to prevent expanding varaibles inside the template file
VARS='$PRJ_NAME:$BRANCH:$HTTP_PORT:$HTTPS_PORT:$HOME'

OUTPUT="docker-compose.$BRANCH.yml"
echo "# Generated by $0" > "$OUTPUT"
envsubst "$VARS" < docker-compose-template.txt >> "$OUTPUT"

echo "Generate a new docker compose file: $OUTPUT"
