# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taoist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videourl',
            name='time_start_download',
            field=models.DateTimeField(null=True),
        ),
    ]
